ucdavis/Sloth

Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Models/TransactionViewModels/TransactionsReturnedViewModel.cs, Sloth.Web/Startup.cs, Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/Transactions/Index.cshtml
Seems to be working pretty okay, updating url via both the datepicker and input focus events. 
Issue #100
=> Add from-to datepicker inputs to filter transactions

.gitignore, Sloth.Web/Views/Transactions/Details.cshtml
Was going to sort via linq, but then bootstrap-datatable would through a fit if I didn't involve him. I caved.
=> Make transfer sorting consistent

.gitignore, Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Models/TransactionViewModels/TransactionsViewModel.cs, Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Transactions/Index.cshtml, Sloth.Web/wwwroot/scss/fa5-power-transforms.scss, Sloth.Web/wwwroot/scss/site.scss
Issue #115 
Not the prettiest, but then again, neither was the previous.
Before:
After:
I added an scss file to enable that nifty icon overlay. It's essentially a polyfill for some features not available in the free version of font-awesome. I didn't find it in any CDN's.
=> Add button for launching WebHook

Sloth.Web/Controllers/ScrubbersController.cs, Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Models/ScrubberViewModels/ScrubberDetailsViewModel.cs, Sloth.Web/Models/TransactionViewModels/TransactionsIndexViewModel.cs, Sloth.Web/Models/TransactionViewModels/TransactionsTableViewModel.cs, Sloth.Web/Views/Scrubbers/Details.cshtml, Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Transactions/Index.cshtml, Sloth.Web/Views/Transactions/NeedApproval.cshtml
There were three different views that included the partial view _TransactionsTable and needed to be modified, along with corresponding controller actions, to accommodate changes to it.
Closes #123
=> Add a TransactionsTableViewModel

Sloth.Api/Logging/LoggingConfiguration.cs, Sloth.Api/Sloth.Api.csproj, Sloth.Api/Startup.cs, Sloth.Api/Swagger/SecurityRequirementsOperationFilter.cs, Sloth.Api/web.config, Sloth.Core/Services/StorageService.cs, Sloth.Core/Sloth.Core.csproj, Sloth.Integrations.Cybersource/Clients/ReportClient.cs, Sloth.Integrations.Cybersource/Sloth.Integrations.Cybersource.csproj, Sloth.Jobs.Core/Logging/LoggingConfiguration.cs, Sloth.Jobs.Core/Sloth.Jobs.Core.csproj, Sloth.Jobs.CyberSource.BankReconcile/Sloth.Jobs.CyberSource.BankReconcile.csproj, Sloth.Jobs.Kfs.ScrubberUpload/Sloth.Jobs.Kfs.ScrubberUpload.csproj, Sloth.Test/Sloth.Test.csproj, Sloth.Web/.eslintignore, Sloth.Web/Controllers/SourcesController.cs, Sloth.Web/Logging/LoggingConfiguration.cs, Sloth.Web/Program.cs, Sloth.Web/Sloth.Web.csproj, Sloth.Web/Startup.cs, Sloth.Web/npm-shrinkwrap.json, Sloth.Web/package.json, Sloth.Web/webpack.config.js, Sloth.Web/wwwroot/scss/site.scss, Sloth.Xml/Sloth.Xml.csproj, azure-pipelines.yml, lgtm.yml
This is a biggie. I'm sure there will be questions.
For the dependency upgrades, the serilog and azure blob were the most significant. I verified that Stackify was receiving log messages from my tests and that azure blob upload/download is functioning.
I haven't done anything to test the jobs. That system is still a little foreign to me, so I'm hoping @jSylvestre can do some testing. But I don't expect there to be any issues with them.
I'm not sure if anything will need to be done on the Azure release pipeline. Should we just merge to master and see what happens? Or should I temporarily update the pipeline to get its artifacts from this branch?
=> Swe/net core3.1

Sloth.Api/Sloth.Api.csproj, Sloth.Web/Controllers/WebHooksController.cs
Trying to address FileNotFoundException using an explicit package reference
=> Troubleshoot api

Sloth.Api/Sloth.Api.csproj, Sloth.Core/Sloth.Core.csproj, Sloth.Jobs.Core/Sloth.Jobs.Core.csproj, Sloth.Web/Sloth.Web.csproj
Seeing if 3.1.5 works after having made all apps publish with explicit win-x86 runtime (self-contained)
=> Upgrade back to 3.1.5

Sloth.Core/Jobs/KfsScrubberUploadJob.cs
so one failure doesn't break everything?
=> Do a try inside the group/source

Sloth.Core/Configuration/CybersourceOptions.cs, Sloth.Core/Jobs/KfsScrubberUploadJob.cs, Sloth.Core/Services/CyberSourceBankReconcileService.cs, Sloth.Core/Services/KfsScrubberService.cs, Sloth.Integrations.Cybersource/Clients/ReportClient.cs, Sloth.Web/appsettings.json
closes #101 
This does not yet store a given blob's uri. I'll open another issue for that, as it would be useful to allow downloading of original report.
=> Save cybersource reports to azure blob storage

Sloth.Core/Domain/CybersourceBankReconcileJobRecord.cs, Sloth.Core/Domain/KfsScrubberUploadJobRecord.cs, Sloth.Core/Domain/Transaction.cs, Sloth.Core/Jobs/CybersourceBankReconcileJob.cs, Sloth.Core/Jobs/KfsScrubberUploadJob.cs, Sloth.Core/Services/CyberSourceBankReconcileService.cs, Sloth.Jobs.CyberSource.BankReconcile/Program.cs, Sloth.Jobs.Kfs.ScrubberUpload/Program.cs, Sloth.Sql/dbo/Tables/Transactions.sql, Sloth.Web/Controllers/JobsController.cs, Sloth.Web/Models/JobViewModels/CybersourceBankReconcileJobViewModel.cs, Sloth.Web/Models/JobViewModels/CybersourceBankReconcileJobsViewModel.cs, Sloth.Web/Models/JobViewModels/JobsFilterModel.cs, Sloth.Web/Models/JobViewModels/KfsScrubberJobViewModel.cs, Sloth.Web/Models/JobViewModels/KfsScrubberJobsViewModel.cs, Sloth.Web/Views/Jobs/CybersourceBankReconcile.cshtml, Sloth.Web/Views/Jobs/CybersourceBankReconcileDetails.cshtml, Sloth.Web/Views/Jobs/KfsScrubberUpload.cshtml, Sloth.Web/Views/Jobs/KfsScrubberUploadDetails.cshtml
Adds some foreign keys from Transactions to the JobRecord tables.
Adds transactions table to Job details pages.
Adds a checkbox filter limiting results to Jobs with transactions.
closes #134
=> Link Jobs to Transactions

Sloth.Web/Sloth.Web.csproj, Sloth.Web/Startup.cs, Sloth.Web/Views/Jobs/CybersourceBankReconcile.cshtml, Sloth.Web/Views/Jobs/KfsScrubberUpload.cshtml
I also added `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` because I'm tired of having to restart the app for every single cshtml tweak.
=> Fix job filtering regression

Sloth.Api/Identity/ApiKeyMiddleware.cs, Sloth.Core/Jobs/CybersourceBankReconcileJob.cs, Sloth.Core/Jobs/KfsScrubberUploadJob.cs, Sloth.Core/Services/CyberSourceBankReconcileService.cs, Sloth.Web/Controllers/SuperController.cs
=> Async all the EF Core things

Sloth.Jobs.CyberSource.BankReconcile/Program.cs
Forgot to register this dependency.
Job-specific appsettings.json may need to be updated for Storage settings in both test and prod.
=> Register IStorageService for Sloth.Jobs.CyberSource.BankReconcile

Sloth.Jobs.CyberSource.BankReconcile/Program.cs
I actually tested it this time.
=> Configure StorageServiceOptions in reconcile job

Sloth.Sql/dbo/Tables/Blobs.sql
UploadedDate column name somehow got out of sync with entity property.
=> Make Blobs.sql consistent with db

Sloth.Web/Controllers/TransactionsController.cs
It generated a DocumentNumber during a reversal in sloth-test.
I wasn't sure if wrapping in a db transaction was necessary, but that's how `CyberSourceBankReconcileService.ProcessReport` was doing it.
=> Generate DocumentNumber during reversal.

Sloth.Core/Data/DbInitializer.cs
Shouldn't be hit on Prod as there are already users
=> Remove John from setup code.

Sloth.Core/SlothDbContext.cs, Sloth.Web/Controllers/AccountController.cs, Sloth.Web/Controllers/HomeController.cs, Sloth.Web/Controllers/SuperController.cs, Sloth.Web/Handlers/VerifyTeamPermissionHandler.cs, Sloth.Web/Helpers/RoleHelpers.cs, Sloth.Web/Views/Home/TeamIndex.cshtml, Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/Shared/_LoginPartial.cshtml, Sloth.Web/Views/Teams/Index.cshtml, Sloth.Web/Views/_ViewImports.cshtml
adds a system for determining team roles for a given user.  added some filters so users can only see things their team roles allow. 
closes #185, #186, #188
=> emulation, user auth filtering, logout fix

Sloth.Web/Controllers/TeamsController.cs
=> redirect to newly created team index

Sloth.Core/Domain/Integration.cs, Sloth.Core/Domain/Source.cs, Sloth.Core/Migrations/20220718180309_SourcesAndIntegrations.Designer.cs, Sloth.Core/Migrations/20220718180309_SourcesAndIntegrations.cs, Sloth.Core/Services/AccountValidationService.cs, Sloth.Core/Services/AggieEnterpriseService.cs, Sloth.Web/Controllers/SourcesController.cs, Sloth.Web/Models/SourceViewModels/SourceViewModel.cs, Sloth.Web/Views/Integrations/Create.cshtml, Sloth.Web/Views/Integrations/Edit.cshtml, Sloth.Web/Views/Sources/Create.cshtml, Sloth.Web/Views/Sources/Edit.cshtml
Allows CRUD of Sources and Integrations so they work for AE too.  Basically sources are easy, they just require a lot less info than before.  Had to update the db to remove a lot of previously required fields.  Integrations use account numbers, so updated the views and models to handle the new formats.  Added some helper text too.  BTW it turns out these accounts have never been validated.    I added #209 in case we want to do some validation-on-save in the future.
=> Updates to Source and Integrations for AE

Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Transactions/Details.cshtml, Sloth.Web/Views/Transactions/_AeDetails.cshtml, Sloth.Web/Views/Transactions/_KfsDetails.cshtml
=> Jcs/ae UI changes20220719

Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Transactions/_AeDetails.cshtml, Sloth.Web/Views/Transactions/_KfsDetails.cshtml
=> Transaction Date Pacific and journal requestId

Sloth.Web/Views/Transactions/Index.cshtml, Sloth.Web/Views/Transactions/NeedApproval.cshtml
=> default sort by transaction date.

Sloth.Core/Services/AggieEnterpriseService.cs
=> Use KFS Tracking number

Sloth.Web/Views/Transactions/Index.cshtml, Sloth.Web/Views/Transactions/NeedApproval.cshtml
=> Remove Big Search Table. Use Placeholder text on existing one.

Sloth.Core/Services/AggieEnterpriseService.cs, Sloth.Core/Sloth.Core.csproj
PPM segment validate no longer takes an accounting date. (Also returns segment string)
=> AE Schema changed.

Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Transactions/Details.cshtml
=> Use real data for activity timeline

Sloth.Web/Views/Shared/_Layout.cshtml
=> Update jquery stuff to the latest

Sloth.Web/Controllers/JobsController.cs, Sloth.Web/Views/Jobs/CybersourceBankReconcileDetails.cshtml, Sloth.Web/Views/Shared/_TransactionsTable.cshtml
Get the slug for transactions so clickable table gets correct routing
=> Jobs page doesn't have a team.

Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/Transactions/_AeDetails.cshtml, Sloth.Web/Views/Transactions/_KfsDetails.cshtml
Disable if they don't have them
=> check permissions for details page actions.

Sloth.Api/Controllers/v1/TransactionsController.cs, Sloth.Api/Controllers/v2/TransactionsController.cs, Sloth.Api/Models/CreateTransactionViewModel.cs, Sloth.Api/Models/v2/CreateTransactionViewModel.cs, Sloth.Core/Services/CyberSourceBankReconcileService.cs, Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Views/Shared/_TransactionsTable.cshtml
=> Use Transaction.Description

Sloth.Api/Controllers/v2/TransactionsController.cs
When posting to create transactions from the calling app, validate the team/source
=> Validate team/source

Sloth.Core/Extensions/StringExtensions.cs, Sloth.Core/Services/StorageService.cs, Sloth.Web/Controllers/BlobsController.cs, Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Models/BlobViewModels/BlobDetailsViewModel.cs, Sloth.Web/Models/BlobViewModels/BlobsTableViewModel.cs, Sloth.Web/Models/TransactionViewModels/TransactionDetailsViewModel.cs, Sloth.Web/Models/TransactionViewModels/TransactionsTableScriptViewModel.cs, Sloth.Web/Views/Blobs/Details.cshtml, Sloth.Web/Views/Jobs/Details.cshtml, Sloth.Web/Views/Scrubbers/Details.cshtml, Sloth.Web/Views/Shared/_BlobsTable.cshtml, Sloth.Web/Views/Shared/_BlobsTableScript.cshtml, Sloth.Web/Views/Shared/_TransactionsTableScript.cshtml, Sloth.Web/Views/Transactions/Details.cshtml, Sloth.Web/Views/Transactions/Index.cshtml, Sloth.Web/Views/Transactions/NeedApproval.cshtml
...and deduplicate DataTable init code.
Closes #157
=> Add blob table and detail views

Sloth.Web/Controllers/ReportsController.cs, Sloth.Web/Handlers/VerifyTeamPermissionHandler.cs, Sloth.Web/Models/ReportViewModels/TransactionsReportViewModel.cs, Sloth.Web/Views/Reports/Index.cshtml, Sloth.Web/Views/Reports/StaleTransactions.cshtml, Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/Shared/_ReportsSvgPartial.cshtml, Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Shared/_TransactionsTableScript.cshtml, Sloth.Web/Views/Transactions/NeedApproval.cshtml
=> Add a Stale Transactions report

Sloth.Web/Startup.cs, Sloth.Web/Views/Jobs/Details.cshtml, Sloth.Web/Views/Jobs/JobList.cshtml, Sloth.Web/Views/Reports/Index.cshtml, Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/Shared/_TransactionsTableScript.cshtml
Using "any" as a team placeholder for non-team reports was problematic.
=> Misc Fixes

Sloth.Web/Views/Jobs/Index.cshtml, Sloth.Web/Views/Jobs/JobList.cshtml, Sloth.Web/Views/Reports/Index.cshtml, Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/Teams/Details.cshtml, Sloth.Web/Views/Transactions/Index.cshtml, Sloth.Web/wwwroot/scss/components.scss, Sloth.Web/wwwroot/scss/typography.scss
Minor changes to button states and the cards on reports,jobs
=> button and card fixes

Sloth.Core/Jobs/AggieEnterpriseJournalJob.cs
=> Notify on rejection due to ArgumentException

Sloth.Web/Views/Home/Index.cshtml, Sloth.Web/Views/Shared/_Layout.cshtml, Sloth.Web/Views/System/Index.cshtml, Sloth.Web/Views/Teams/Index.cshtml
I re-used the team-settings class
=> System menu, formatting and cleanup

Sloth.Test/Helpers/CreateValidEntities.cs, Sloth.Web/Controllers/BlobsController.cs, Sloth.Web/Controllers/IntegrationsController.cs, Sloth.Web/Controllers/ScrubbersController.cs, Sloth.Web/Controllers/SourcesController.cs, Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Controllers/WebHooksController.cs
resolves #298 
For some I wasn't sure about where to redirect. Probably not a big deal, since these conditions aren't likely to occur through normal (non-malicious) use.
=> Add slug validations to several controller actions

Sloth.Web/Controllers/TransactionsController.cs
Member Name is something different
=> Track Approve and Approve All

Sloth.Core/Configuration/AggieEnterpriseOptions.cs, Sloth.Core/Services/AggieEnterpriseService.cs, Sloth.Jobs.AggieEnterprise.JournalProcessor/appsettings.json, Sloth.Web/Views/Reports/FailedTransactions.cshtml, Sloth.Web/Views/Shared/_TransactionsTable.cshtml, Sloth.Web/Views/Shared/_TransactionsTableScript.cshtml, Sloth.Web/Views/Transactions/NeedApproval.cshtml
=> Show the amount, include the COAs for searching

Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Views/Transactions/_AeDetails.cshtml, Sloth.Web/Views/Transactions/_KfsDetails.cshtml
=> Multiple related txns indicator

Sloth.Web/Views/Transactions/_AeDetails.cshtml, Sloth.Web/Views/Transactions/_KfsDetails.cshtml
=> Easier to read, still obvious

Sloth.Web/Controllers/TeamsController.cs, Sloth.Web/Views/Teams/Details.cshtml
=> Use correct format for column using @data-sort

Sloth.Api/Controllers/v2/TransactionsController.cs
`/v2/Transactions/processortrackingnumber/{id}`
=> Add new v2 action GetAllByProcessorId

Sloth.Web/Controllers/TeamsController.cs, Sloth.Web/Views/Teams/Details.cshtml
=> Can't have approver and manager roles in the same team

Sloth.Core/Extensions/StringExtensions.cs, Sloth.Core/Jobs/CybersourceBankReconcileJob.cs, Sloth.Core/Services/CyberSourceBankReconcileService.cs, Sloth.Web/Controllers/IntegrationsController.cs
No more null job details.
Also tweaked Integration edits to ensure that CyberSource report api key is base64 encoded.
Closes #342
=> Improve CyberSource job details

Sloth.Core/Jobs/CybersourceBankReconcileJob.cs, Sloth.Core/Services/CyberSourceBankReconcileService.cs
Makes display on job result page a little easier to read.
=> Use lists to hold multiple job result messages

Sloth.Core/Jobs/NotificationJob.cs, Sloth.Jobs.Notifications/Program.cs
Here's my stab at it. Haven't tested.
=> Consolidate notification results into one record

Sloth.Core/Jobs/KfsScrubberUploadJob.cs, Sloth.Web/Controllers/JobsController.cs
but maybe a fix for the scrubber id not being written in the job details
=> Untested, 

Sloth.Web/Controllers/IntegrationsController.cs, Sloth.Web/Views/Integrations/Create.cshtml
=> Add ccoa picker and validation to integration creation

Sloth.Web/Controllers/TransactionsController.cs
=> If for some reason MTN is null, don't use that to find related txns

Sloth.Core/Jobs/AggieEnterpriseJournalJob.cs, Sloth.Core/Services/AggieEnterpriseService.cs, Sloth.Core/Sloth.Core.csproj
Also log it
Going to wait for an Updated AE API
=> Accept warning status.

Sloth.Core/Services/NotificationService.cs, Sloth.Core/Sloth.Core.csproj, Sloth.Core/Views/Emails/DefaultNotification.cshtml, Sloth.Core/Views/Shared/_EmailButton.cshtml, Sloth.Core/Views/Shared/_EmailInnerDetails.cshtml, Sloth.Core/Views/Shared/_EmailLayout.cshtml, Sloth.Jobs.AggieEnterprise.JournalProcessor/Program.cs, Sloth.Jobs.Notifications/Program.cs, Sloth.Web/Startup.cs
I verified that Mjml.Net is fully dotnet, with no js hiding under the covers. And it's fast, as in single-digit milliseconds to render.
=> Use Mjml.Net

Sloth.Api/Logging/LoggingConfiguration.cs, Sloth.Api/Sloth.Api.csproj, Sloth.Jobs.Core/Logging/LoggingConfiguration.cs, Sloth.Jobs.Core/Sloth.Jobs.Core.csproj, Sloth.Web/Logging/LoggingConfiguration.cs, Sloth.Web/Sloth.Web.csproj
without `ConfigureStackifyLogging()` the appsettings won't be applied
=> need to call ConfigureStackifyLogging 

Sloth.Web/Views/Transactions/_AeDetails.cshtml
=> Link Chart String to finjector

Sloth.Api/Controllers/v2/TransactionsController.cs
=> Catch Error

Sloth.Web/Controllers/TransactionsController.cs, Sloth.Web/Views/Transactions/Details.cshtml, Sloth.Web/Views/Transactions/_AeDetails.cshtml
**Approver or admin and Rejected:**
**Dialog:**
**Disabled button if not approver or admin**
=> Resubmit rejected txn

Sloth.Core/Domain/Transaction.cs, Sloth.Web/Controllers/TransactionsController.cs
=> Cancel reversal and activity timeline

Sloth.Web/Controllers/ReportsController.cs, Sloth.Web/Views/Reports/FailedTransactions.cshtml
=> Export stuck transactions
